# shellcheck shell=bash
# tmux.sh - tmux wrapper functions

# Source utils if not already loaded
[[ -z "$AM_DIR" ]] && source "${AM_LIB_DIR:-$(dirname "${BASH_SOURCE[0]}")}/utils.sh"

am_tmux_config_path() {
    # Cache: only generate config once per process
    if [[ -n "${_AM_TMUX_CONF_CACHED:-}" ]]; then
        echo "$_AM_TMUX_CONF_CACHED"
        return
    fi

    am_init

    local am_cmd switch_cmd kill_cmd cycle_cmd index_cmd status_bar_cmd desired_conf
    am_cmd="$AM_ROOT_DIR/am"
    switch_cmd="$AM_ROOT_DIR/bin/switch-last"
    kill_cmd="$AM_ROOT_DIR/bin/kill-and-switch"
    cycle_cmd="$AM_ROOT_DIR/bin/switch-cycle"
    index_cmd="$AM_ROOT_DIR/bin/switch-index"
    status_bar_cmd="$AM_ROOT_DIR/lib/status-bar"

    desired_conf=$(cat <<EOF
# Generated by agent-manager. Edit ~/.tmux.conf for your base tmux settings.
# This config runs on a dedicated tmux server (socket: $AM_TMUX_SOCKET), so
# every session here is an am-* session — bindings don't need an am-* guard.
# Prefix+[ keeps tmux's default copy-mode; prefix+] keeps default paste-buffer.
if-shell '[ -f "$HOME/.tmux.conf" ]' 'source-file "$HOME/.tmux.conf"'
set -g detach-on-destroy off
set -g focus-events on

# Restore tmux defaults for [/] (idempotent on reload — earlier versions of
# this config rebound them to session cycling).
bind [ copy-mode
bind ] paste-buffer -p

# Prefix + a: switch to last used am session
bind a run-shell "$switch_cmd"

# Prefix + Right/Left: cycle next/prev session in canonical (creation-time) order
bind Right run-shell "$cycle_cmd next"
bind Left run-shell "$cycle_cmd prev"

# Prefix + 1-9: jump to sidebar slot N
bind 1 run-shell "$index_cmd 1"
bind 2 run-shell "$index_cmd 2"
bind 3 run-shell "$index_cmd 3"
bind 4 run-shell "$index_cmd 4"
bind 5 run-shell "$index_cmd 5"
bind 6 run-shell "$index_cmd 6"
bind 7 run-shell "$index_cmd 7"
bind 8 run-shell "$index_cmd 8"
bind 9 run-shell "$index_cmd 9"

# Prefix + n: open new-session popup
bind n display-popup -E -w 90% -h 80% "$am_cmd new"

# Prefix + s: open agent manager popup
bind s display-popup -E -w 90% -h 80% "$am_cmd"

# Prefix + h: open the merged session switcher, which includes inactive sessions
bind h display-popup -E -w 90% -h 80% "$am_cmd"

# Prefix + x: kill the current am session and switch to the next most recent one
bind-key -T prefix x run-shell "$kill_cmd #{client_name} #{session_name}"

# Optional alias: :am
set -s command-alias[100] am='display-popup -E -w 90% -h 80% "$am_cmd"'

# Status bar: whole bottom bar acts as a tab switcher. The status-bar script
# precomputes per-session @am_status_left / @am_sidebar / @am_attention
# options, and tmux just reads those — switching sessions is instant because
# no #() job needs to finish first. A hidden invocation in status-right
# triggers periodic refresh at status-interval.
set -g status-interval 5
set -g status-style 'bg=colour234,fg=colour250'
set -g status-left-length 500
set -g status-left '#{@am_status_left}'
set -g status-right-length 120
set -g status-right '#($status_bar_cmd #{session_name})#{@am_attention} #[fg=colour245]%H:%M '

# Refresh options after the active session changes. run-shell -b detaches
# the child so tmux doesn't block on it — switch-client returns immediately
# and the user is in the new session before status-bar finishes. The
# precomputed @am_status_left option already has the right "current"
# highlighting baked in (status-bar writes one per perspective), so the
# visual update is instant; this hook just keeps state glyphs and ages
# fresh between the 5s status-interval ticks.
set-hook -g client-session-changed 'run-shell -b "$status_bar_cmd #{session_name}"'

# Drop tmux's default window list — am sessions use a single window so the
# default 'index:name*' slot is just clutter between tabs and the clock.
set -g window-status-format ''
set -g window-status-current-format ''
set -g window-status-separator ''
set -g status-justify left

# Pane border sidebar: compact session list on the divider between agent and
# shell panes. Reads the @am_sidebar option populated by status-bar.
set -g pane-border-status bottom
set -g pane-border-format '#{?#{pane_at_bottom},,#[align=centre]#{@am_sidebar}}'
set -g pane-border-lines double
set -g pane-border-style 'fg=colour67'
set -g pane-active-border-style 'fg=colour14'

# Clicking a session tab in the status bar switches to that session. Tabs are
# wrapped in #[range=user|<session>]...#[norange] by lib/status-bar, so
# mouse_status_range carries the session name directly. switch-client -t does
# NOT format-expand its target arg, so we shell out via run-shell (whose
# shell-command arg IS format-expanded) instead.
# Border-level click isn't possible — tmux doesn't populate mouse_x/mouse_y
# for MouseDown1Border events.
set -g mouse on
bind -n MouseDown1Status if-shell -F '#{!=:#{mouse_status_range},}' { run-shell "tmux switch-client -t '#{mouse_status_range}' ; tmux refresh-client -S" } { switch-client -t = }
EOF
)

    # Refresh generated config when the repo path or binding format changes.
    if [[ ! -f "$AM_TMUX_CONF" ]] || [[ "$(cat "$AM_TMUX_CONF" 2>/dev/null)" != "$desired_conf" ]]; then
        printf '%s\n' "$desired_conf" > "$AM_TMUX_CONF"

        # If the tmux server is already running, source the updated config
        # so changes (like status-right) take effect without restarting.
        command tmux -L "$AM_TMUX_SOCKET" source-file "$AM_TMUX_CONF" 2>/dev/null || true

        # Clear legacy per-session status-left overrides left over from the old
        # tmux_set_session_status code path so existing sessions pick up the
        # global tab-strip status-left.
        local _legacy_session
        while IFS= read -r _legacy_session; do
            [[ -n "$_legacy_session" ]] || continue
            command tmux -L "$AM_TMUX_SOCKET" set-option -u -t "$_legacy_session" status-left 2>/dev/null || true
            command tmux -L "$AM_TMUX_SOCKET" set-option -u -t "$_legacy_session" status-left-length 2>/dev/null || true
        done < <(command tmux -L "$AM_TMUX_SOCKET" list-sessions -F '#{session_name}' 2>/dev/null \
                    | grep "^${AM_SESSION_PREFIX}" || true)
        command tmux -L "$AM_TMUX_SOCKET" refresh-client -S 2>/dev/null || true
    fi

    _AM_TMUX_CONF_CACHED="$AM_TMUX_CONF"
    echo "$AM_TMUX_CONF"
}

am_tmux() {
    local conf
    conf=$(am_tmux_config_path)
    command tmux -L "$AM_TMUX_SOCKET" -f "$conf" "$@"
}

am_tmux_is_current_server() {
    [[ "${TMUX:-}" == *"/${AM_TMUX_SOCKET},"* ]]
}

# Check if a tmux session exists
# Usage: tmux_session_exists <name>
tmux_session_exists() {
    local name="$1"
    am_tmux has-session -t "$name" 2>/dev/null
}

# Create a new tmux session (detached)
# Usage: tmux_create_session <name> <directory>
tmux_create_session() {
    local name="$1"
    local directory="$2"

    if tmux_session_exists "$name"; then
        log_error "Session '$name' already exists"
        return 1
    fi

    # Create with explicit dimensions to work around tmux sizing bugs in detached sessions
    # https://github.com/tmux/tmux/issues/3060
    am_tmux new-session -d -s "$name" -c "$directory" -x 200 -y 60
}

# Kill a tmux session
# Usage: tmux_kill_session <name>
tmux_kill_session() {
    local name="$1"

    if ! tmux_session_exists "$name"; then
        log_warn "Session '$name' does not exist"
        return 1
    fi

    tmux_cleanup_logs "$name"
    am_tmux kill-session -t "$name"
}

# Stream pane output to a log file using tmux pipe-pane
tmux_enable_pipe_pane() {
    local session="$1"
    local pane="$2"
    local log_file="$3"

    am_tmux pipe-pane -t "${session}:${pane}" -o "${AM_LIB_DIR}/strip-ansi >> ${log_file}"
}

# Remove log directory and legacy sidebar cache for a session
tmux_cleanup_logs() {
    local name="$1"
    local log_dir="/tmp/am-logs/${name}"

    if [[ -d "$log_dir" ]]; then
        rm -rf "$log_dir"
    fi
    rm -f "/tmp/am-sidebar/${name}"
}

# Attach to a tmux session
# Usage: tmux_attach <name>
tmux_attach() {
    local name="$1"

    if ! tmux_session_exists "$name"; then
        log_error "Session '$name' does not exist"
        return 1
    fi

    if am_tmux_is_current_server; then
        # Already inside the agent-manager tmux server, switch client in place.
        am_tmux switch-client -t "$name"
    else
        # Attach to the dedicated agent-manager server. Clear TMUX so nesting
        # inside an unrelated tmux server attaches a new client instead.
        TMUX='' am_tmux attach-session -t "$name"
    fi
}

# Get a tmux session field value
# Usage: _tmux_get_session_field <name> <format_token>
_tmux_get_session_field() {
    local name="$1" format="$2"
    am_tmux list-sessions -F "#{session_name} #{$format}" 2>/dev/null \
        | grep "^${name} " | cut -d' ' -f2
}

# Get session activity timestamp (seconds since epoch)
tmux_get_activity() { _tmux_get_session_field "$1" session_activity; }

# Get session creation time (seconds since epoch)
tmux_get_created() { _tmux_get_session_field "$1" session_created; }

# List all agent-manager sessions (those with AM_SESSION_PREFIX)
# Usage: tmux_list_am_sessions
# Returns: newline-separated session names
tmux_list_am_sessions() {
    am_tmux list-sessions -F '#{session_name}' 2>/dev/null \
        | grep "^${AM_SESSION_PREFIX}" \
        || true
}

# List all agent-manager sessions in canonical sidebar order: creation time
# ascending, so newly created sessions always appear at the end. Stable — only
# changes on session create/kill. Numbered slots and cycling keybindings
# follow this order.
# Usage: am_session_order
# Returns: newline-separated session names
am_session_order() {
    am_tmux list-sessions -F '#{session_created} #{session_name}' 2>/dev/null \
        | grep " ${AM_SESSION_PREFIX}" \
        | sort -k1,1n -k2,2 \
        | awk '{print $2}' \
        || true
}

# Regenerate per-session status-bar options (@am_sidebar, @am_attention) for
# every am session and force a client-wide redraw. Call after creating or
# killing a session so the status bar and pane border update immediately
# instead of waiting for the 5s status-interval refresh.
#
# A single status-bar invocation already writes options for every session in
# its final loop, so this just runs it once — the previous per-session loop
# performed the exact same work N times.
# Usage: am_refresh_sidebar_cache
am_refresh_sidebar_cache() {
    local script="${AM_LIB_DIR:-$(dirname "${BASH_SOURCE[0]}")}/status-bar"
    [[ -x "$script" ]] || return 0
    "$script" >/dev/null 2>&1 || true

    # Clean up stale files from the old pane-border implementation. That path
    # used tmux #() jobs, which are cached and caused delayed middle-bar updates.
    local cache_dir="/tmp/am-sidebar" cache_file
    if [[ -d "$cache_dir" ]]; then
        for cache_file in "$cache_dir"/"${AM_SESSION_PREFIX}"*; do
            [[ -e "$cache_file" ]] || continue
            rm -f "$cache_file"
        done
        rmdir "$cache_dir" 2>/dev/null || true
    fi

    am_tmux refresh-client -S 2>/dev/null || true
}

# List all agent-manager sessions with activity info
# Usage: tmux_list_am_sessions_with_activity
# Returns: "name activity_timestamp" per line, sorted by activity (most recent first)
tmux_list_am_sessions_with_activity() {
    am_tmux list-sessions -F '#{session_activity} #{session_name}' 2>/dev/null \
        | grep " ${AM_SESSION_PREFIX}" \
        | sort -rn \
        | awk '{print $2, $1}' \
        || true
}

# Send keys to a tmux session
# Usage: tmux_send_keys <name> <keys...>
tmux_send_keys() {
    local name="$1"
    shift
    am_tmux send-keys -t "$name" "$@"
}

# Paste literal text into a tmux pane without shell escaping issues.
# Usage: tmux_paste_text <target-pane> <text>
tmux_paste_text() {
    local target="$1"
    local text="$2"

    printf '%s' "$text" | am_tmux load-buffer -
    am_tmux paste-buffer -d -t "$target"
}

# Return the current command running in a pane.
# Usage: tmux_pane_current_command <target-pane>
tmux_pane_current_command() {
    local target="$1"
    am_tmux display-message -p -t "$target" '#{pane_current_command}'
}

# Return the title of a pane (set by the application via escape sequences).
# Usage: tmux_pane_title <target-pane>
tmux_pane_title() {
    local target="$1"
    am_tmux display-message -p -t "$target" '#{pane_title}'
}

# Resolve a logical pane name to a tmux pane target.
# Usage: tmux_session_pane_target <session_name> [agent|shell]
tmux_session_pane_target() {
    local session_name="$1"
    local pane_name="${2:-agent}"

    case "$pane_name" in
        agent|top) echo "${session_name}:.{top}" ;;
        shell|bottom) echo "${session_name}:.{bottom}" ;;
        *) return 1 ;;
    esac
}

# Return the optional streamed log file path for a session pane.
# Usage: tmux_session_pane_log_file <session_name> [agent|shell]
tmux_session_pane_log_file() {
    local session_name="$1"
    local pane_name="${2:-agent}"

    case "$pane_name" in
        agent|top) echo "/tmp/am-logs/${session_name}/agent.log" ;;
        shell|bottom) echo "/tmp/am-logs/${session_name}/shell.log" ;;
        *) return 1 ;;
    esac
}

# Capture the visible history of a pane.
# Usage: tmux_capture_pane <target-pane> [lines]
# If lines is specified, captures only the last N lines using -S -N flag.
# Otherwise captures entire history with -S - -E -.
tmux_capture_pane() {
    local target="$1"
    local lines="${2:-}"

    if [[ -n "$lines" && "$lines" =~ ^[0-9]+$ ]]; then
        am_tmux capture-pane -t "$target" -p -e -S "-${lines}" -E - 2>/dev/null
    else
        am_tmux capture-pane -t "$target" -p -e -S - -E - 2>/dev/null
    fi
}

# Count agent-manager sessions
# Usage: tmux_count_am_sessions
tmux_count_am_sessions() {
    local sessions
    sessions=$(tmux_list_am_sessions)
    if [[ -z "$sessions" ]]; then
        echo 0
    else
        echo "$sessions" | wc -l | tr -d ' '
    fi
}
