# shellcheck shell=bash
# tmux.sh - tmux wrapper functions

# Source utils if not already loaded
[[ -z "$AM_DIR" ]] && source "${AM_LIB_DIR:-$(dirname "${BASH_SOURCE[0]}")}/utils.sh"

am_tmux_config_path() {
    # Cache: only generate config once per process
    if [[ -n "${_AM_TMUX_CONF_CACHED:-}" ]]; then
        echo "$_AM_TMUX_CONF_CACHED"
        return
    fi

    am_init

    local am_cmd switch_cmd kill_cmd cycle_cmd index_cmd status_right_cmd desired_conf
    am_cmd="$AM_ROOT_DIR/am"
    switch_cmd="$AM_ROOT_DIR/bin/switch-last"
    kill_cmd="$AM_ROOT_DIR/bin/kill-and-switch"
    cycle_cmd="$AM_ROOT_DIR/bin/switch-cycle"
    index_cmd="$AM_ROOT_DIR/bin/switch-index"
    status_right_cmd="$AM_ROOT_DIR/lib/status-right"

    desired_conf=$(cat <<EOF
# Generated by agent-manager. Edit ~/.tmux.conf for your base tmux settings.
if-shell '[ -f "$HOME/.tmux.conf" ]' 'source-file "$HOME/.tmux.conf"'
set -g detach-on-destroy off

# Prefix + a: switch to last used am session
bind a if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$switch_cmd"' 'display-message "am shortcuts are active only in am-* sessions"'

# Prefix + ]/[: cycle next/prev session (fall back to default paste/copy-mode outside am)
bind ] if-shell -F '#{m:am-*,#{session_name}}' { switch-client -n ; refresh-client -S } 'paste-buffer -p'
bind [ if-shell -F '#{m:am-*,#{session_name}}' { switch-client -p ; refresh-client -S } 'copy-mode'

# Prefix + 1-9: jump to sidebar slot N
bind 1 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 1"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 2 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 2"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 3 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 3"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 4 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 4"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 5 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 5"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 6 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 6"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 7 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 7"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 8 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 8"' 'display-message "am shortcuts are active only in am-* sessions"'
bind 9 if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$index_cmd 9"' 'display-message "am shortcuts are active only in am-* sessions"'

# Prefix + n: open new-session popup
bind n if-shell -F '#{m:am-*,#{session_name}}' 'display-popup -E -w 90% -h 80% "$am_cmd new"' 'display-message "am shortcuts are active only in am-* sessions"'

# Prefix + s: open agent manager popup
bind s if-shell -F '#{m:am-*,#{session_name}}' 'display-popup -E -w 90% -h 80% "$am_cmd"' 'display-message "am shortcuts are active only in am-* sessions"'

# Prefix + H: open restore session popup
bind h if-shell -F '#{m:am-*,#{session_name}}' 'display-popup -E -w 90% -h 80% "$am_cmd restore"' 'display-message "am shortcuts are active only in am-* sessions"'

# Prefix + x: kill the current am session and switch to the next most recent one
bind-key -T prefix x if-shell -F '#{m:am-*,#{session_name}}' 'run-shell "$kill_cmd #{client_name} #{session_name}"' 'confirm-before -p "kill-pane #P? (y/n)" kill-pane'

# Optional alias: :am
set -s command-alias[100] am='display-popup -E -w 90% -h 80% "$am_cmd"'

# Status bar: show sessions as indexed sidebar
set -g status-interval 5
set -g status-right-length 200
set -g status-right '#($status_right_cmd #{session_name})'
EOF
)

    # Refresh generated config when the repo path or binding format changes.
    if [[ ! -f "$AM_TMUX_CONF" ]] || [[ "$(cat "$AM_TMUX_CONF" 2>/dev/null)" != "$desired_conf" ]]; then
        printf '%s\n' "$desired_conf" > "$AM_TMUX_CONF"

        # If the tmux server is already running, source the updated config
        # so changes (like status-right) take effect without restarting.
        command tmux -L "$AM_TMUX_SOCKET" source-file "$AM_TMUX_CONF" 2>/dev/null || true
    fi

    _AM_TMUX_CONF_CACHED="$AM_TMUX_CONF"
    echo "$AM_TMUX_CONF"
}

am_tmux() {
    local conf
    conf=$(am_tmux_config_path)
    command tmux -L "$AM_TMUX_SOCKET" -f "$conf" "$@"
}

am_tmux_is_current_server() {
    [[ "${TMUX:-}" == *"/${AM_TMUX_SOCKET},"* ]]
}

# Check if a tmux session exists
# Usage: tmux_session_exists <name>
tmux_session_exists() {
    local name="$1"
    am_tmux has-session -t "$name" 2>/dev/null
}

# Create a new tmux session (detached)
# Usage: tmux_create_session <name> <directory>
tmux_create_session() {
    local name="$1"
    local directory="$2"

    if tmux_session_exists "$name"; then
        log_error "Session '$name' already exists"
        return 1
    fi

    # Create with explicit dimensions to work around tmux sizing bugs in detached sessions
    # https://github.com/tmux/tmux/issues/3060
    am_tmux new-session -d -s "$name" -c "$directory" -x 200 -y 60
}

_tmux_bool_label() {
    case "${1:-}" in
        1|true|yes|on) echo "yes" ;;
        *) echo "no" ;;
    esac
}

_tmux_status_value() {
    local value="${1:-}"
    value=${value//$'\n'/ }
    echo "${value:-"-"}"
}

# Set a per-session status-left string with session metadata.
# Usage: tmux_set_session_status <name> <directory> <branch> <worktree_name> <yolo_mode> <sandbox_mode>
tmux_set_session_status() {
    local name="$1"
    local directory="$2"
    local branch="$3"
    local worktree_name="$4"
    local yolo_mode="$5"
    local sandbox_mode="$6"

    local dir_label branch_label status_left
    dir_label=$(_tmux_status_value "$(dir_basename "${directory:-$name}")")
    branch_label=$(_tmux_status_value "$branch")

    status_left="#[bold]#{session_name}#[default] ${dir_label}:${branch_label}"
    [[ -n "$worktree_name" ]] && status_left="${status_left} (${worktree_name})"
    [[ "$yolo_mode" == "true" ]] && status_left="${status_left} yolo"
    [[ "$sandbox_mode" == "true" ]] && status_left="${status_left} sandbox"
    status_left="${status_left} "

    am_tmux set-option -t "$name" status-left-length 160 >/dev/null
    am_tmux set-option -t "$name" status-left "$status_left" >/dev/null
}

# Kill a tmux session
# Usage: tmux_kill_session <name>
tmux_kill_session() {
    local name="$1"

    if ! tmux_session_exists "$name"; then
        log_warn "Session '$name' does not exist"
        return 1
    fi

    tmux_cleanup_logs "$name"
    am_tmux kill-session -t "$name"
}

# Stream pane output to a log file using tmux pipe-pane
tmux_enable_pipe_pane() {
    local session="$1"
    local pane="$2"
    local log_file="$3"

    am_tmux pipe-pane -t "${session}:${pane}" -o "${AM_LIB_DIR}/strip-ansi >> ${log_file}"
}

# Remove log directory for a session
tmux_cleanup_logs() {
    local name="$1"
    local log_dir="/tmp/am-logs/${name}"

    if [[ -d "$log_dir" ]]; then
        rm -rf "$log_dir"
    fi
}

# Attach to a tmux session
# Usage: tmux_attach <name>
tmux_attach() {
    local name="$1"

    if ! tmux_session_exists "$name"; then
        log_error "Session '$name' does not exist"
        return 1
    fi

    if am_tmux_is_current_server; then
        # Already inside the agent-manager tmux server, switch client in place.
        am_tmux switch-client -t "$name"
    else
        # Attach to the dedicated agent-manager server. Clear TMUX so nesting
        # inside an unrelated tmux server attaches a new client instead.
        TMUX='' am_tmux attach-session -t "$name"
    fi
}

# Get a tmux session field value
# Usage: _tmux_get_session_field <name> <format_token>
_tmux_get_session_field() {
    local name="$1" format="$2"
    am_tmux list-sessions -F "#{session_name} #{$format}" 2>/dev/null \
        | grep "^${name} " | cut -d' ' -f2
}

# Get session activity timestamp (seconds since epoch)
tmux_get_activity() { _tmux_get_session_field "$1" session_activity; }

# Get session creation time (seconds since epoch)
tmux_get_created() { _tmux_get_session_field "$1" session_created; }

# List all agent-manager sessions (those with AM_SESSION_PREFIX)
# Usage: tmux_list_am_sessions
# Returns: newline-separated session names
tmux_list_am_sessions() {
    am_tmux list-sessions -F '#{session_name}' 2>/dev/null \
        | grep "^${AM_SESSION_PREFIX}" \
        || true
}

# List all agent-manager sessions in canonical sidebar order. Matches tmux's
# native session iteration (switch-client -n/-p) so the numbered slots and
# the cycling keybindings agree. Stable — only changes on session create/kill.
# Usage: am_session_order
# Returns: newline-separated session names
am_session_order() {
    am_tmux list-sessions -F '#{session_name}' 2>/dev/null \
        | grep "^${AM_SESSION_PREFIX}" \
        || true
}

# List all agent-manager sessions with activity info
# Usage: tmux_list_am_sessions_with_activity
# Returns: "name activity_timestamp" per line, sorted by activity (most recent first)
tmux_list_am_sessions_with_activity() {
    am_tmux list-sessions -F '#{session_activity} #{session_name}' 2>/dev/null \
        | grep " ${AM_SESSION_PREFIX}" \
        | sort -rn \
        | awk '{print $2, $1}' \
        || true
}

# Send keys to a tmux session
# Usage: tmux_send_keys <name> <keys...>
tmux_send_keys() {
    local name="$1"
    shift
    am_tmux send-keys -t "$name" "$@"
}

# Paste literal text into a tmux pane without shell escaping issues.
# Usage: tmux_paste_text <target-pane> <text>
tmux_paste_text() {
    local target="$1"
    local text="$2"

    printf '%s' "$text" | am_tmux load-buffer -
    am_tmux paste-buffer -d -t "$target"
}

# Return the current command running in a pane.
# Usage: tmux_pane_current_command <target-pane>
tmux_pane_current_command() {
    local target="$1"
    am_tmux display-message -p -t "$target" '#{pane_current_command}'
}

# Return the title of a pane (set by the application via escape sequences).
# Usage: tmux_pane_title <target-pane>
tmux_pane_title() {
    local target="$1"
    am_tmux display-message -p -t "$target" '#{pane_title}'
}

# Resolve a logical pane name to a tmux pane target.
# Usage: tmux_session_pane_target <session_name> [agent|shell]
tmux_session_pane_target() {
    local session_name="$1"
    local pane_name="${2:-agent}"

    case "$pane_name" in
        agent|top) echo "${session_name}:.{top}" ;;
        shell|bottom) echo "${session_name}:.{bottom}" ;;
        *) return 1 ;;
    esac
}

# Return the optional streamed log file path for a session pane.
# Usage: tmux_session_pane_log_file <session_name> [agent|shell]
tmux_session_pane_log_file() {
    local session_name="$1"
    local pane_name="${2:-agent}"

    case "$pane_name" in
        agent|top) echo "/tmp/am-logs/${session_name}/agent.log" ;;
        shell|bottom) echo "/tmp/am-logs/${session_name}/shell.log" ;;
        *) return 1 ;;
    esac
}

# Capture the visible history of a pane.
# Usage: tmux_capture_pane <target-pane> [lines]
# If lines is specified, captures only the last N lines using -S -N flag.
# Otherwise captures entire history with -S - -E -.
tmux_capture_pane() {
    local target="$1"
    local lines="${2:-}"

    if [[ -n "$lines" && "$lines" =~ ^[0-9]+$ ]]; then
        am_tmux capture-pane -t "$target" -p -e -S "-${lines}" -E - 2>/dev/null
    else
        am_tmux capture-pane -t "$target" -p -e -S - -E - 2>/dev/null
    fi
}

# Count agent-manager sessions
# Usage: tmux_count_am_sessions
tmux_count_am_sessions() {
    local sessions
    sessions=$(tmux_list_am_sessions)
    if [[ -z "$sessions" ]]; then
        echo 0
    else
        echo "$sessions" | wc -l | tr -d ' '
    fi
}
